[project]
name = "scripts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.10.12"
dependencies = [
    "pymongo>=4.14.1",
    "pyproj>=3.7.1",
    "requests>=2.32.5",
    "tqdm>=4.67.1",
]
