name: CI Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  code-quality-checks:
    name: Code Quality Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Setup pnpm
        uses: pnpm/action-setup@master

      - name: Setup Node.js
        uses: actions/setup-node@main
        with:
          node-version-file: ./.node-version

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        
      - name: Run Format & Lint Check with Biome
        run: pnpm biome ci ./src

      - name: Run Type Check
        run: pnpm tsc --noEmit
